WebApplication1/Controllers/BlogController.cs
using Blog.Models;
using ImTools;
using OpenXmlPowerTools;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;
using WebApplication1.Repository;

namespace WebApplication1.Controllers
{
    public class BlogController : Controller
    {
        private BlogContext db = new BlogContext();
        #region Atributos 
        private PostRepository _repo;

       

        #endregion
        #region Constructor
        public BlogController()
        {
            _repo = new PostRepository();
        }
        #endregion
        #region Index       
        // GET: Blog

        public ActionResult Index(string Filtros)


        {
            //var model = _repo.TraerTodos();
            //return View(model);

            if (!string.IsNullOrEmpty(Filtros))
            {
                var query = db.blogPosts.Where(o => o.Titulo.Contains(Filtros)).ToList();
                return View(query);
            }
            else
            {
                var model = _repo.TraerTodos();
                return View(model);
                //return View(db.blogPosts.Take(5).ToList());
            }






        }

        #endregion
        #region Detalles

        // GET: Blog/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            using (var db = new BlogContext())
            {
                Post post = db.blogPosts.Find(id);
                if (post == null)
                {
                    return HttpNotFound();
                }
                return View(post);
            }
        }
        #endregion
        #region C
        // GET: Blog/Create
        public ActionResult Create()
        {
            Post myNewPost = new Post(); 
            return View(myNewPost);
        }


        public ActionResult convertirImagen(int CodigoCliente)
        {
            var imagenCliente = db.blogPosts.Where(z => z.Id == CodigoCliente).FirstOrDefault();
            return File(imagenCliente.Imagen, "image/jpeg");
        }



        // POST: Blog/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Post model, HttpPostedFileBase imagenCliente)
        {
            //HttpPostedFileBase File = Request.Files["ImageData"];
            //Byte[] imageBytes = ConvertToBytes(upload);

            if (imagenCliente != null && imagenCliente.ContentLength > 0)
            {
                byte[] imageData = null;
                using (var binaryReader = new BinaryReader(imagenCliente.InputStream))
                {
                    imageData = binaryReader.ReadBytes(imagenCliente.ContentLength);
                }
                //setear la imagen a la entidad que se creara
                model.Imagen = imageData;
            }





            try
            {
                if (ModelState.IsValid)
                {

                                  
                   

                    _repo.Alta(model);
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }
            return View(model);
        }

        #endregion
        #region Editar
        // GET: Blog/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);
            }
            using (var db = new BlogContext())
            {
                Post post = db.blogPosts.Find(id);
                if (post == null)
                {
                    return HttpNotFound();
                }
                return View(post);
            }

        }


      




        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Titulo,Contenido,Categoria,FechaDeCreacion,Estado")] Post post, HttpPostedFileBase imagenCliente)
        {


            if (imagenCliente != null && imagenCliente.ContentLength > 0)
            {
                byte[] imageData = null;
                using (var binaryReader = new BinaryReader(imagenCliente.InputStream))
                {
                    imageData = binaryReader.ReadBytes(imagenCliente.ContentLength);
                }
                //setear la imagen a la entidad que se creara
               post.Imagen = imageData;
            }

            if (ModelState.IsValid)
            {
                using (var db = new BlogContext())
                {
                    db.Entry(post).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            return View(post);
        }

        #endregion
        #region Eliminar
     // GET: Posts/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            using (var db = new BlogContext())
            {
                Post post = db.blogPosts.Find(id);
                if (post == null)
                {
                    return HttpNotFound();
                }
                return View(post);
            }
        }

        // POST: Posts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            using (var db = new BlogContext())
            {
                Post post = db.blogPosts.Find(id);
                db.blogPosts.Remove(post);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
        }

        public ActionResult ElegirEliminar(string searchString)
        {
            using (var db = new BlogContext())
            {
                var post = from d in db.blogPosts
                           select d;

                if (!String.IsNullOrEmpty(searchString))
                {
                    post = post.Where(s => s.Titulo.Contains(searchString));
                }
                
                return View(post.ToList());
            }
        }

        #endregion
        #region Categorias
        public ActionResult Economia()
        {
            using (var db = new BlogContext())
            {
                var articuloEconomia = db.blogPosts.Where(x => x.Categoria == "Economia");
 
                return View(articuloEconomia.ToList());
            }
        }

        public ActionResult Politica()
        {
            using (var db = new BlogContext())
            {
                var articuloPolitica = db.blogPosts.Where(x => x.Categoria == "Politica");
                return View(articuloPolitica.ToList());
            }
        }

        public ActionResult Deporte()
        {
            using (var db = new BlogContext())
            {
                var articuloDeporte = db.blogPosts.Where(x => x.Categoria == "Deporte");
                return View(articuloDeporte.ToList());
            }
        }

        public ActionResult Otro()
        {
            using (var db = new BlogContext())
            {
                var articuloOtro = db.blogPosts.Where(x => x.Categoria == "Otro");
                return View(articuloOtro.ToList());
            }
        }
        #endregion
        #region Listar para Edicion

        public ActionResult ElegirEdicion(string searchString)
        {
            using (var db = new BlogContext())
            {
                var post = from d in db.blogPosts
                           select d;

                if (!String.IsNullOrEmpty(searchString))
                {
                    post = post.Where(s => s.Titulo.Contains(searchString));
                    if (post.Count() == 0)
                    {
                        return Content("Titulo no encontrado");
                    }

                }

               
                return View(post.ToList());
            }
        }

        #endregion
    }
}

WebApplication1/Views/Blog/Create.cshtml
@model Blog.Models.Post

@{
    ViewBag.Title = "Crear nuevo post para el Blog";
}

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm("Create", "Blog", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Post</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Titulo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Titulo, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Titulo, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Contenido, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Contenido, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Contenido, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Categoria, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @*Html.EditorFor(model => model.Categoria, new { htmlAttributes = new { @class = "form-control" } })*@
            <select name="@Html.NameFor(model => model.Categoria)">
                <option value="" selected disabled> Seleccionar la categoria:              </option>
                <option>Economia </option>
                <option>Deportes </option>
                <option>Politica </option>
                <option>Otro </option>
            </select>
            @Html.ValidationMessageFor(model => model.Categoria, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.FechaDeCreacion, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.FechaDeCreacion, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.FechaDeCreacion, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group row">
        <div class="col-md-10">
            <label asp-for="Estado"></label>
        </div>
        <div class="col-md-10">
            <select asp-for="Estado" class="form-control">
                <option value=true>Activo</option>
                <option value=false>Inactivo</option>
            </select>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Imagen, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="imagenCliente" />
        </div>
    </div>


    


    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Añadir Post al Blog" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Volver a la pagina principal", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApplication1/Views/Blog/Delete.cshtml
@model Blog.Models.Post

@{
    ViewBag.Title = "Eliminar Post";
}

<h2>@ViewBag.Title</h2>

<h3>Esta seguro que lo quiere eliminar?</h3>
<div>
    <h4>Post</h4>
    <hr />

    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Titulo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Contenido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Contenido)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Categoria)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Categoria)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaDeCreacion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaDeCreacion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Imagen)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Imagen)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Estado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estado)
        </dd>


       

        <dd>
            <img width="50" height="50" src="@Url.Action("convertirImagen", "Blog", new {CodigoCliente = Model.Id})" />
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WebApplication1/Views/Blog/Deporte.cshtml
@model IEnumerable<Blog.Models.Post>

@{
    ViewBag.Title = "Deporte";
}

<h2>@ViewBag.Title</h2>

<table class="table">

    @foreach (var item in Model)
    {
        <tr>
            <td>
                <b style="color:aqua; font-size:large; ">  @Html.DisplayFor(modelItem => item.Titulo)</b> <br />
                @Html.DisplayFor(modelItem => item.Contenido)
            </td>
        </tr>

        <tr>
            <td>
                Categoria: <a href="~/Blog/@item.Categoria"> @Html.DisplayFor(modelItem => item.Categoria)</a>
            </td>
            <td>
            </td>
            <td>
                Fecha de Creacion:  @Html.DisplayFor(modelItem => item.FechaDeCreacion)
            </td>

        </tr>
    }
</table>
<div>
    @Html.ActionLink("Volver a la pagina principal", "Index")
</div>

WebApplication1/Views/Blog/Details.cshtml
@model Blog.Models.Post

@{
    ViewBag.Title = "Contenido del Post";
}

<h2>@ViewBag.Title</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Titulo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Contenido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Contenido)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Categoria)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Categoria)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaDeCreacion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaDeCreacion)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Imagen)
        </dt>

        <dd>
            <img width="50" height="50" src="@Url.Action("convertirImagen", "Blog", new {CodigoCliente = Model.Id})" />
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.Id }, new { @class = "btn btn-success" })  |
    @Html.ActionLink("Volver a la pagina principal", "Index")
</p>

WebApplication1/Views/Blog/Economia.cshtml
@model IEnumerable<Blog.Models.Post>

@{
    ViewBag.Title = "Economia";
}

<h2>Economia</h2>

<table class="table">

    @foreach (var item in Model)
    {
        <tr>
            <td>
                <b style="color:aqua; font-size:large; ">  @Html.DisplayFor(modelItem => item.Titulo)</b> <br />
                @Html.DisplayFor(modelItem => item.Contenido)
            </td>
        </tr>

        <tr>
            <td>
                Categoria: <a href="~/Blog/@item.Categoria"> @Html.DisplayFor(modelItem => item.Categoria)</a>
            </td>
            <td>
            </td>
            <td>
                Fecha de Creacion:  @Html.DisplayFor(modelItem => item.FechaDeCreacion)
            </td>
        
        </tr>
    }
    </table>
<div>
    @Html.ActionLink("Volver a la pagina principal", "Index")
</div>

WebApplication1/Views/Blog/Edit.cshtml
@model Blog.Models.Post

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Editar los Post</h2>


@using (Html.BeginForm("Edit", "Blog", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Posts</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        @Html.LabelFor(model => model.Titulo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Titulo, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Titulo, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Contenido, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Contenido, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Contenido, "", new { @class = "text-danger" })
        </div>
    </div>



    <div class="form-group">
        @Html.LabelFor(model => model.Categoria, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <select name="@Html.NameFor(model => model.Categoria)">
                <option value="" selected disabled> Seleccionar la categoria:              </option>
                <option>Economia </option>
                <option>Deportes </option>
                <option>Politica </option>
                <option>Otro </option>
            </select>
            @Html.ValidationMessageFor(model => model.Categoria, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.FechaDeCreacion, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.FechaDeCreacion, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.FechaDeCreacion, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group row">
        <div class="col-md-10">
            <label asp-for="Estado"></label>
        </div>
        <div class="col-10">
            <select asp-for="Estado" class="form-control">
                <option value=true>Activo</option>
                <option value=false>Inactivo</option>
            </select>
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Imagen Actual", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <img width="280" height="250" src="@Url.Action("convertirImagen", "Blog", new {CodigoCliente = Model.Id})" />
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Cambiar Imagen", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="imagenCliente" />
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Guardar Cambios" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApplication1/Views/Blog/ElegirEdicion.cshtml
@model IEnumerable<Blog.Models.Post>
@{
    ViewBag.Title = "Editar Posts";
}

<h2>@ViewBag.Title</h2>
<form asp-controller="Post" asp-action="ElegirEdicion">
    <p>
        Busqueda por Titulo: <input type="text" name="SearchString">
        <input type="submit" value="Buscar" />
    </p>

</form>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Titulo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Contenido)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Categoria)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FechaDeCreacion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Imagen)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.Estado)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.Titulo)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Contenido)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Categoria)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.FechaDeCreacion)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Imagen)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Estado)
    </td>

    <td>
        @Html.ActionLink("Editar", "Edit", new { id = item.Id })
</tr>
    }

</table>

WebApplication1/Views/Blog/ElegirEliminar.cshtml
@model IEnumerable<Blog.Models.Post>
@{
    ViewBag.Title = "Eliminar Posts";
}

<h2>@ViewBag.Title</h2>
<form asp-controller="Post" asp-action="ElegirEdicion">
    <p>
        Busqueda por Titulo: <input type="text" name="SearchString">
        <input type="submit" value="Buscar" />
    </p>

</form>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Titulo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Contenido)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Categoria)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FechaDeCreacion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Imagen)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.Estado)
        </th>

        <th></th>
    </tr>

    @foreach (var item in Model)
    {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.Titulo)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Contenido)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Categoria)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.FechaDeCreacion)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Imagen)
    </td>

    <td>
        @Html.DisplayFor(modelItem => item.Estado)
    </td>
    <td>
        @Html.ActionLink("Eliminar", "Delete", new { id = item.Id })
</tr>
    }

</table>

WebApplication1/Views/Blog/Index.cshtml
@model IEnumerable<Blog.Models.Post>
@{
 }
<h2>@ViewBag.Title</h2>
<div class="row">
    <div class="col-6">
        <h2 class="text-primary"> Listado de Post </h2>
    </div>
    <p>
        <a href="@Url.Action("Create","Blog")" class="btn btn-primary">Nuevo Posteo</a>
    </p>
</div>
<form asp-controller="BlogController" asp-action="Index">
    <p>
        Titulo: <input type="text" name="Filtros">
        <input type="submit" value="Buscar" />
    </p>
</form>

<table class="table">
    @foreach (var item in Model)
    {
        <tr>
            <td>
                <b style="color:forestgreen; font-size:large; "> @Html.DisplayFor(modelItem => item.Titulo) </b> <br />
            </td>
            <td>
                Categoria: <a href="~/Blog/@item.Categoria"> @Html.DisplayFor(modelItem => item.Categoria)</a>
            </td>

            <td>
                Fecha de Creacion:  @Html.DisplayFor(modelItem => item.FechaDeCreacion)
            </td>

            <td>
                <img width="50" height="50" src="@Url.Action("convertirImagen", "Blog", new {CodigoCliente = item.Id})" />
            </td>
            @*<td>
                @if (item.Estado == true)
                {
                    <p>Activo</p>
                }
                else
                {
                    <p>Inactivo</p>
                }

            </td>*@
        
            <td>
                @Html.ActionLink("Ver", "Details", new { id = item.Id },new {@class="btn btn-info" })|
                @Html.ActionLink("Eliminar", "Delete", new { id = item.Id }, new { @class = "btn btn-danger" })|
                @Html.ActionLink("Editar", "Edit", new { id = item.Id }, new { @class = "btn btn-success" })|

            </td>
        </tr>

     }

</table>

WebApplication1/Views/Blog/Otro.cshtml
@model IEnumerable<Blog.Models.Post>

@{
    ViewBag.Title = "Otro";
}

<h2>@ViewBag.Title</h2>

<table class="table">

    @foreach (var item in Model)
    {
        <tr>
            <td>
                <b style="color:aqua; font-size:large; ">  @Html.DisplayFor(modelItem => item.Titulo)</b> <br />
                @Html.DisplayFor(modelItem => item.Contenido)
            </td>
        </tr>

        <tr>
            <td>
                Categoria: <a href="~/Blog/@item.Categoria"> @Html.DisplayFor(modelItem => item.Categoria)</a>
            </td>
            <td>
            </td>
            <td>
                Fecha de Creacion:  @Html.DisplayFor(modelItem => item.FechaDeCreacion)
            </td>

        </tr>
    }
</table>
<div>
    @Html.ActionLink("Volver a la pagina principal", "Index")
</div>

WebApplication1/Views/Blog/Politica.cshtml
@model IEnumerable<Blog.Models.Post>

@{
    ViewBag.Title = "Politica";
}

<h2>@ViewBag.Title</h2>

<table class="table">

    @foreach (var item in Model)
    {
        <tr>
            <td>
                <b style="color:aqua; font-size:large; ">  @Html.DisplayFor(modelItem => item.Titulo)</b> <br />
                @Html.DisplayFor(modelItem => item.Contenido)
            </td>
        </tr>

        <tr>
            <td>
                Categoria: <a href="~/Blog/@item.Categoria"> @Html.DisplayFor(modelItem => item.Categoria)</a>
            </td>
            <td>
            </td>
            <td>
                Fecha de Creacion:  @Html.DisplayFor(modelItem => item.FechaDeCreacion)
            </td>

        </tr>
    }
</table>
<div>
    @Html.ActionLink("Volver a la pagina principal", "Index")
</div>